### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by someoneidoknow**
why the hell is there a * in the gitignore this sin is not forgiveable

### CODE REVIEW

**Comment by Apethesis** [comment]
This is the worst pull request I have ever seen in the history of me being on Github. Instantly denied, goodbye.

**Review by 0mori1 — APPROVED** [review]
no idea what this does 👍

**Comment by someoneidoknow** [comment]
buddy i was not done

**Comment by 0mori1** [comment]
rewinded

**Pull request closed without merging**
