### PR TITLE
cooking for blockheads and spice of life carrot edition added

### PR DESCRIPTION
**Pull request by 0mori1**

### CODE REVIEW

**Review by Why2312 — APPROVED** [review]
ok i want to cook me-

**Review by GazaAudio — APPROVED** [review]
honestly i think this would be a great idea for all of us, eyecubed might say otherwise

**Comment by 0mori1** [comment]
jesse, we need to cook

**Comment by 0mori1** [comment]
we might need applecore if we dont have that

**Comment by Why2312** [comment]
jesse we need to make yakebuguwire

**Comment by 0mori1** [comment]
jesse our reactor exploded what the fuck did you do

**Review by Apethesis — APPROVED** [review]
im approving this cause of the comments you silly retards made

**Pull request merged**
