### PR TITLE
fuck them ores bruh

### PR DESCRIPTION
**Pull request by eyecubed**
many more to go, dont disable thermal or ill kill

### CODE REVIEW

**Comment by Apethesis** [comment]
doesnt thermal have that one claim bypass? can we fix that somehow

**Comment by eyecubed** [comment]
disable reservoir, simple

**Comment by Apethesis** [comment]
i'll approve when you disable reservoir

**Comment by Apethesis** [comment]
actually do that in a separate pr ima approve this

**Review by Apethesis — APPROVED** [review]
it gud

**Review by GazaAudio — COMMENTED** [review]
gotta be a no from me

**Review by GazaAudio — APPROVED** [review]
changed my mind

**Review by 0mori1 — APPROVED** [review]
no one wants a krillion of the same ore

**Pull request merged**
