### PR TITLE
Make Mekanism more expensive.

### PR DESCRIPTION
**Pull request by Apethesis**

### CODE REVIEW

**Review by Why2312 — APPROVED** [review]
i feel a lot better, still quite a pain

**Review by 0mori1 — APPROVED** [review]
the when nuclearcraft

**Comment by Apethesis** [comment]
thats good

**Review by GazaAudio — APPROVED** [review]
ah shit bro,it's all over my hands so sory for the long wiat to get the review haha only got 1 hand

**Pull request merged**
