### PR TITLE
phospor is forked, most mod incompats should be fixed

### PR DESCRIPTION
**Pull request by eyecubed**
performance mod dump

### CODE REVIEW

**Comment by Apethesis** [comment]
i've had issues with phosphor before, so i dont really want this to be added
btw wtf is sledgehammer

**Comment by eyecubed** [comment]
smashes the stupid out of the server 
https://modrinth.com/plugin/sledgehammer
exactly does what it says

**Comment by eyecubed** [comment]
also might wanna read the name

**Comment by eyecubed** [comment]
image

**Comment by Apethesis** [comment]
ehhhh, not willing to risk it

**Comment by eyecubed** [comment]
this is the reason why i started hating you in the first place

**Review by 0mori1 — APPROVED** [review]
as long this doesnt cause stupid issues like LoliASM did with SGCraft its fine

**Comment by 0mori1** [comment]
ermmmm what the scallop

**Review by Apethesis — CHANGES_REQUESTED** [review]
remove idletweaks (already have a mod that does the same) and phosphor (cause of mod incompat risks)
then i'll approve it

**Comment by Apethesis** [comment]
aight its clear you wont do it, closing the pr

**Pull request closed without merging**
