### PR TITLE
Revert "cooking for blockheads and spice of life carrot edition added"

### PR DESCRIPTION
**Pull request by Apethesis**
Reverts MechSorcery/MechanicalSorcery#
i doesnt rwants

### CODE REVIEW

**Comment by 0mori1** [comment]
why

**Comment by Apethesis** [comment]
to realisticism

**Comment by 0mori1** [comment]
NOT

**Comment by 0mori1** [comment]
WRONG MODS YOU TALKING ABOUT

**Comment by 0mori1** [comment]
IS EATING UNIQUE FOODS FOR EXTRA HEALTH AND HAVING AN ACTUAL KITCHEN TOO REAILISTIC FOR YOU!??!?!??!?!?!?!

**Comment by Apethesis** [comment]
yes

**Pull request closed without merging**
