### PR TITLE
Skin mod for cracked server

### PR DESCRIPTION
**Pull request by GazaAudio**
Skin mod for cracked server

### CODE REVIEW

**Comment by Why2312** [comment]
I don’t really want cracked

**Comment by GazaAudio** [comment]
then we only get 1-2 members on the server everyday

**Comment by Apethesis** [comment]
our whole universe was in a hot dense state

**Comment by Apethesis** [comment]
then nearly 14 billion years ago expansion started wait

**Comment by 0mori1** [comment]
i no want crack

**Comment by ADMIIM** [comment]
sing with me "Snort white snow!"

**Pull request closed without merging**
